# Generated by Django 2.0.4 on 2019-02-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20180331_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('by', models.CharField(max_length=50)),
                ('link', models.URLField(max_length=150)),
                ('body', models.CharField(max_length=300, null=True)),
                ('github', models.URLField(max_length=250)),
                ('language', models.TextField()),
            ],
        ),
    ]
