# Generated by Django 2.0.4 on 2019-02-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github',
        ),
        migrations.AddField(
            model_name='project',
            name='git',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
