# Generated by Django 2.0.4 on 2019-02-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20190211_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='git',
        ),
    ]
