# Generated by Django 2.0.4 on 2019-02-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_remove_project_git'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slink',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
